### ISSUE TITLE
CI/CD todo list

### ISSUE THREAD

**Issue by stewartboogert** [bdsim-collaboration/bdsim#3]
- [x] complete transfer of user development branches
- [ ] develop clang format lint config for codebase
- [x] Distribute/release documentation (read the docs and zipped)
- [x] Matrix build docker images
- [x] Pre-built artefacts?
- [x] Move over python helper packages 
- [x] pybdsim
- [x] pymadx
- [x] pytransport
- [x] email bdsim mailing list on move to GitHub
- [X] setup test data repository
- [X] pyflubl
- [X] test for manual build #21 
- [x] Readme for Mac_geant4
- [x] Logo avatar
- [x] strip back Mac brew requirements 
- [x] Markdown readme #9
- [x] Mailing list on readme
- [x] execute ctest within runners #10 
- [x] merge GitHub actions and trigger of upstream PR 
- [x] delete testing repo from bdsim-collaboration
- [x] macOS-15 and geant4.11.3 configurations 
- [x] Move sboogert/ docker images to docker organisation #8 
- [x] Development instructions to update docker and Macg4

**Comment by stewartboogert** [comment]
Basically done. Clang format should be separate.
